[package]
name = "necronomicon"
version = "0.1.1"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1.24.2", features = ["full"] }
libp2p = { version = "0.50.0", features = ["full"] }
