name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2 
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: release-please-action
  linux-x86_64:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          rustup update
          cargo build --release
      - name: package
        run: |
          cd target/release
          strip necronomicon
          chmod +x necronomicon
          tar -c necronomicon | gzip > necronomicon.tar.gz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: necronomicon-${{ needs.release.outputs.tag_name }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
          asset_path: target/release/necronomicon.tar.gz
          upload_url: ${{ needs.release.outputs.upload_url }}
  windows-x86_64:
    runs-on: windows-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          rustup update
          cargo build --release
      - name: package
        run: |
          cd target/release
          7z a -tzip necronomicon.zip necronomicon.exe
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: necronomicon-${{ needs.release.outputs.tag_name }}-windows-x86_64.zip
          asset_content_type: application/zip
          asset_path: target/release/netmon-server.zip
          upload_url: ${{ needs.release.outputs.upload_url }}
  